### ISSUE TITLE
PXE Unable to locate a configuration file caused by filename generator bug

### ISSUE THREAD

**Issue by TribalNightOwl** [RedHatOfficial/ocp4-helpernode#132]
Given the following (notice the MAC addresses last character, first is a lowercase 'c' the others are uppercase):
```
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.1.220"
  macaddr: "00:50:56:01:01:0c"
masters:
  - name: "master0"
    ipaddr: "192.168.1.221"
    macaddr: "00:50:56:01:01:0D"
  - name: "master1"
    ipaddr: "192.168.1.222"
    macaddr: "00:50:56:01:01:0E"
  - name: "master2"
    ipaddr: "192.168.1.223"
    macaddr: "00:50:56:01:01:0F"
workers:
  - name: "worker0"
    ipaddr: "192.168.1.224"
    macaddr: "00:50:56:01:01:10"
  - name: "worker1"
    ipaddr: "192.168.1.225"
    macaddr: "00:50:56:01:01:11"
```

The following pxelinux.cfg files are created:

![image](https://user-images.githubusercontent.com/34578120/88993817-f388da80-d2b4-11ea-89ff-b7545b8d41c3.png)

When I use a capital 'C' for the MAC address of the bootstrap machine:

```
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.1.220"
  macaddr: "00:50:56:01:01:0C"
masters:
  - name: "master0"
    ipaddr: "192.168.1.221"
    macaddr: "00:50:56:01:01:0D"
  - name: "master1"
    ipaddr: "192.168.1.222"
    macaddr: "00:50:56:01:01:0E"
  - name: "master2"
    ipaddr: "192.168.1.223"
    macaddr: "00:50:56:01:01:0F"
workers:
  - name: "worker0"
    ipaddr: "192.168.1.224"
    macaddr: "00:50:56:01:01:10"
  - name: "worker1"
    ipaddr: "192.168.1.225"
    macaddr: "00:50:56:01:01:11"
```

The files created are:

![image](https://user-images.githubusercontent.com/34578120/88993860-13200300-d2b5-11ea-80f0-fb640b0be201.png)

Notice how the file name now has a capital 'C', but this only occurs for the bootstrap machine (maybe because it is the first on the list?)

But this causes the error: Unable to locate a configuration file:

![image](https://user-images.githubusercontent.com/34578120/88993890-1fa45b80-d2b5-11ea-86ac-b0345dc5a521.png)

When all MAC addresses have lowercase:
```
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.1.220"
  macaddr: "00:50:56:01:01:0c"
masters:
  - name: "master0"
    ipaddr: "192.168.1.221"
    macaddr: "00:50:56:01:01:0d"
  - name: "master1"
    ipaddr: "192.168.1.222"
    macaddr: "00:50:56:01:01:0e"
  - name: "master2"
    ipaddr: "192.168.1.223"
    macaddr: "00:50:56:01:01:0f"
workers:
  - name: "worker0"
    ipaddr: "192.168.1.224"
    macaddr: "00:50:56:01:01:10"
  - name: "worker1"
    ipaddr: "192.168.1.225"
    macaddr: "00:50:56:01:01:11"
```

The resulting files are all in lowercase:

![image](https://user-images.githubusercontent.com/34578120/88993914-30ed6800-d2b5-11ea-980a-5e46ee1f47eb.png)

which causes a successful boot:

![image](https://user-images.githubusercontent.com/34578120/88993940-3fd41a80-d2b5-11ea-8a0b-f7bf93495d2c.png)

Maybe worth investigating:
https://github.com/RedHatOfficial/ocp4-helpernode/blob/fa3a9019f77ef181a2ec50d538ca733e4ca6c5c9/tasks/main.yml#L239

A temporary alternative would be to suggest to use only lowercase for MAC addresses.
