### ISSUE TITLE
UEFI update on devel error

### ISSUE THREAD

**Issue by christianh814** [RedHatOfficial/ocp4-helpernode#197]
@tosmi So testing this, I'm getting this error...

```
TASK [copy UEFI shim to grub2 tftpboot/grub2 directory] ************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Source /boot/efi/EFI/redhat/shimx64.efi not found"}

RUNNING HANDLER [restart bind] *************************************************

RUNNING HANDLER [restart haproxy] **********************************************

RUNNING HANDLER [restart httpd] ************************************************

RUNNING HANDLER [restart dhcpd] ************************************************

RUNNING HANDLER [restart tftp] *************************************************

RUNNING HANDLER [restart nfs] **************************************************

PLAY RECAP *********************************************************************
localhost                  : ok=48   changed=32   unreachable=0    failed=1    skipped=16   rescued=1    ignored=
```

This is the "default testing" vars.yaml file.

```
---
disk: vda
helper:
  name: "helper"
  ipaddr: "192.168.7.77"
dns:
  domain: "example.com"
  clusterid: "ocp4"
  forwarder1: "8.8.8.8"
  forwarder2: "8.8.4.4"
dhcp:
  router: "192.168.7.1"
  bcast: "192.168.7.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.7.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.7.20"
  macaddr: "52:54:00:60:72:67"
masters:
  - name: "master0"
    ipaddr: "192.168.7.21"
    macaddr: "52:54:00:e7:9d:67"
  - name: "master1"
    ipaddr: "192.168.7.22"
    macaddr: "52:54:00:80:16:23"
  - name: "master2"
    ipaddr: "192.168.7.23"
    macaddr: "52:54:00:d5:1c:39"
workers:
  - name: "worker0"
    ipaddr: "192.168.7.11"
    macaddr: "52:54:00:f4:26:a1"
  - name: "worker1"
    ipaddr: "192.168.7.12"
    macaddr: "52:54:00:82:90:00"
setup_registry:
  deploy: true
  autosync_registry: false
  registry_image: docker.io/library/registry:2
  local_repo: "ocp4/openshift4"
  product_repo: "openshift-release-dev"
  release_name: "ocp-release"
  release_tag: "4.6.1-x86_64"
chronyconfig:
  enabled: true
  content:
    - server: 0.centos.pool.ntp.org
      options: iburst
    - server: 1.centos.pool.ntp.org
      options: iburst
```
