### ISSUE TITLE
Ansible error in generate_ssh_keys.yaml

### ISSUE THREAD

**Issue by bassplay3r** [RedHatOfficial/ocp4-helpernode#25]
I added the ocp4_helpernode to my CI and it was working great but yesterday I started to see this error 

Installed:
  ansible.noarch 0:2.4.2.0-2.el7          git.x86_64 0:1.8.3.1-21.el7_7

Dependency Installed:
  PyYAML.x86_64 0:3.10-11.el7
  libyaml.x86_64 0:0.1.4-11.el7_0
  perl.x86_64 4:5.16.3-294.el7_6
  perl-Carp.noarch 0:1.26-244.el7
  perl-Encode.x86_64 0:2.51-7.el7
  perl-Error.noarch 1:0.17020-2.el7
  perl-Exporter.noarch 0:5.68-3.el7
  perl-File-Path.noarch 0:2.09-2.el7
  perl-File-Temp.noarch 0:0.23.01-3.el7
  perl-Filter.x86_64 0:1.49-3.el7
  perl-Getopt-Long.noarch 0:2.40-3.el7
  perl-Git.noarch 0:1.8.3.1-21.el7_7
  perl-HTTP-Tiny.noarch 0:0.033-3.el7
  perl-PathTools.x86_64 0:3.40-5.el7
  perl-Pod-Escapes.noarch 1:1.04-294.el7_6
  perl-Pod-Perldoc.noarch 0:3.20-4.el7
  perl-Pod-Simple.noarch 1:3.28-4.el7
  perl-Pod-Usage.noarch 0:1.63-3.el7
  perl-Scalar-List-Utils.x86_64 0:1.27-248.el7
  perl-Socket.x86_64 0:2.010-4.el7
  perl-Storable.x86_64 0:2.45-3.el7
  perl-TermReadKey.x86_64 0:2.30-20.el7
  perl-Text-ParseWords.noarch 0:3.29-4.el7
  perl-Time-HiRes.x86_64 4:1.9725-3.el7
  perl-Time-Local.noarch 0:1.2300-2.el7
  perl-constant.noarch 0:1.27-2.el7
  perl-libs.x86_64 4:5.16.3-294.el7_6
  perl-macros.x86_64 4:5.16.3-294.el7_6
  perl-parent.noarch 1:0.225-244.el7
  perl-podlators.noarch 0:2.5.1-3.el7
  perl-threads.x86_64 0:1.87-4.el7
  perl-threads-shared.x86_64 0:1.43-6.el7
  python-babel.noarch 0:0.9.6-8.el7
  python-backports.x86_64 0:1.0-8.el7
  python-backports-ssl_match_hostname.noarch 0:3.5.0.1-1.el7
  python-cffi.x86_64 0:1.6.0-5.el7
  python-enum34.noarch 0:1.0.4-1.el7
  python-httplib2.noarch 0:0.9.2-1.el7
  python-idna.noarch 0:2.4-1.el7
  python-ipaddress.noarch 0:1.0.16-2.el7
  python-jinja2.noarch 0:2.7.2-4.el7
  python-markupsafe.x86_64 0:0.11-10.el7
  python-paramiko.noarch 0:2.1.1-9.el7
  python-passlib.noarch 0:1.6.5-2.el7
  python-ply.noarch 0:3.4-11.el7
  python-pycparser.noarch 0:2.14-1.el7
  python-setuptools.noarch 0:0.9.8-7.el7
  python-six.noarch 0:1.9.0-2.el7
  python2-cryptography.x86_64 0:1.7.2-2.el7
  python2-jmespath.noarch 0:0.9.0-3.el7
  python2-pyasn1.noarch 0:0.1.9-7.el7
  rsync.x86_64 0:3.1.2-6.el7_6.1
  sshpass.x86_64 0:1.06-2.el7

Complete!
Cloning into 'ocp4-helpernode'...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- openssh_keypair:
  ^ here

The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- openssh_keypair:
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- openssh_keypair:
  ^ here

I'm invoking it as 

```
!/bin/sh
yum -y install ansible git
git clone https://github.com/RedHatOfficial/ocp4-helpernode
cp vars.yaml ocp4-helpernode/
cd ocp4-helpernode
ansible-playbook -e @vars.yaml tasks/main.yml
```

My vars.yaml
```
---
disk: vda
helper:
  name: "helper"
  ipaddr: "192.168.7.77"
  networkifacename: "eth1"
dns:
  domain: "foo.bar.com"
  clusterid: "cim6xufuaruaidi"
  forwarder1: "10.193.159.254"
  forwarder2: "10.102.76.214"
dhcp:
  router: "192.168.7.1"
  bcast: "192.168.7.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.7.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.7.20"
  macaddr: "52:54:00:a5:50:2c"
masters:
  - name: "master0"
    ipaddr: "192.168.7.21"
    macaddr: "52:54:00:2a:44:b3"
  - name: "master1"
    ipaddr: "192.168.7.22"
    macaddr: "52:54:00:80:13:25"
  - name: "master2"
    ipaddr: "192.168.7.23"
    macaddr: "52:54:00:98:92:db"
workers:
  - name: "worker0"
    ipaddr: "192.168.7.11"
    macaddr: "52:54:00:5d:50:ed"
  - name: "worker1"
    ipaddr: "192.168.7.12"
    macaddr: "52:54:00:31:5f:f7"
```

**Comment by bassplay3r** [comment]
I think I see the problem 
openssh_keypair – Generate OpenSSH private and public keys
New in version 2.8.

Installed:
ansible.noarch 0:2.4.2.0-2.el7

**Comment by bassplay3r** [comment]
[root@helper ~]# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
[root@helper ~]#

**Comment by bassplay3r** [comment]
[root@helper ~]# sh -x configure_helper.sh
+ yum -y install centos-release-ansible-29 git
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.wdc1.us.leaseweb.net
 * centos-ansible-29: mirror.cs.vt.edu
 * extras: mirror.cc.columbia.edu
 * updates: repos-va.psychz.net
Package centos-release-ansible-29-1-1.el7.noarch already installed and latest version
Package git-1.8.3.1-21.el7_7.x86_64 already installed and latest version
Nothing to do
+ rm -rf ocp4-helpernode
+ git clone https://github.com/RedHatOfficial/ocp4-helpernode
Cloning into 'ocp4-helpernode'...
remote: Enumerating objects: 207, done.
remote: Counting objects: 100% (207/207), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 207 (delta 93), reused 129 (delta 42), pack-reused 0
Receiving objects: 100% (207/207), 144.99 KiB | 0 bytes/s, done.
Resolving deltas: 100% (93/93), done.
+ cp vars.yaml ocp4-helpernode/
+ cd ocp4-helpernode
+ ansible-playbook -e @vars.yaml tasks/main.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- openssh_keypair:
  ^ here


The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- openssh_keypair:
  ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/root/ocp4-helpernode/tasks/generate_ssh_keys.yaml': line 7, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- openssh_keypair:
  ^ here

[root@helper ~]#

**Comment by bassplay3r** [comment]
Sigh 
[root@helper ocp4-helpernode]# ansible-playbook --version
ansible-playbook 2.4.2.0
  config file = /root/ocp4-helpernode/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

**Comment by whowutwut** [comment]
HAHA,  @bassplay3r  I hit the SAME thing yesterday trying to bring my environment up to the latest code..  saw this issue  in my email notifications today

I decided to just use pip3 to resolve this...  So instead of doing install of "ansible" which pulls in 2.4... I am installing `python3-pip` and then use pip module to install Ansible, which i think gives you 2.9...  

After CentOS installed, i have a play to configure it... doing something like this: 

```
- name: install rpm packages on helper node
  become: true
  yum:
    name:
      - python3-pip
    state: present

- name: install pip packages
  pip:
    name:
      - ansible
    executable: pip3
```

Hope this helps!
