### ISSUE TITLE
RFE: Move RHCOS installation target disk to the masters/workers/bootstrap section

### ISSUE THREAD

**Issue by christianh814** [RedHatOfficial/ocp4-helpernode#68]
Currently [there's a global setting](https://github.com/RedHatOfficial/ocp4-helpernode/blob/master/docs/vars-doc.md#disk-to-install-rhcos) for which disk RHCOS is installed to. This setting eventually makes it's way to the PXE config as kernel parameters.

We should have this as a specific setting to each node section. Example:

```
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.7.20"
  macaddr: "52:54:00:60:72:67"
  disk: vda
masters:
  - name: "master0"
    ipaddr: "192.168.7.21"
    macaddr: "52:54:00:e7:9d:67"
    disk: vda
  - name: "master1"
    ipaddr: "192.168.7.22"
    macaddr: "52:54:00:80:16:23"
    disk: vda
  - name: "master2"
    ipaddr: "192.168.7.23"
    macaddr: "52:54:00:d5:1c:39"
    disk: vda
workers:
  - name: "worker0"
    ipaddr: "192.168.7.11"
    macaddr: "52:54:00:f4:26:a1"
    disk: vda
  - name: "worker1"
    ipaddr: "192.168.7.12"
    macaddr: "52:54:00:82:90:00"
    disk: vda
  - name: "worker2"
    ipaddr: "192.168.7.13"
    macaddr: "52:54:00:8e:10:34"
    disk: vda
```

This way you can have "mixed disk"  environment (say, for example, one of your workers has NVMe disks or if you're using FC and each node has a UUID as the disk name)
