### ISSUE TITLE
Error AnsibleUndefinedVariable: 'registry_host' is undefined even though setup_registry is not configured

### ISSUE THREAD

**Issue by deathemperor** [RedHatOfficial/ocp4-helpernode#96]
My vars.yml:

```yaml
staticips: true
disk: vda
helper:
  name: "helper"
  ipaddr: "192.168.8.217"
  networkifacename: "ens192"
dns:
  domain: "domain.com"
  clusterid: "ocp4"
  forwarder1: "8.8.8.8"
  forwarder2: "8.8.4.4"
dhcp:
  router: "192.168.8.1"
  bcast: "192.168.8.255"
  netmask: "255.255.255.0"
  poolstart: "192.168.8.10"
  poolend: "192.168.7.30"
  ipid: "192.168.7.0"
  netmaskid: "255.255.255.0"
bootstrap:
  name: "bootstrap"
  ipaddr: "192.168.8.219"
  macaddr: "52:54:00:60:72:67"
masters:
  - name: "master0"
    ipaddr: "192.168.8.210"
    macaddr: "52:54:00:e7:9d:67"
  - name: "master1"
    ipaddr: "192.168.8.211"
    macaddr: "52:54:00:80:16:23"
  - name: "master2"
    ipaddr: "192.168.8.212"
    macaddr: "52:54:00:d5:1c:39"
workers:
  - name: "worker0"
    ipaddr: "192.168.8.200"
    macaddr: "52:54:00:f4:26:a1"
  - name: "worker1"
    ipaddr: "192.168.8.224"
    macaddr: "52:54:00:82:90:00"
other:
  - name: "non-cluster-vm"
    ipaddr: "192.168.8.217"
#setup_registry:
#  deploy: false
#  autosync_registry: false
#  registry_image: docker.io/library/registry:2
#  local_repo: "ocp4/openshift4"
#  product_repo: "openshift-release-dev"
#  release_name: "ocp-release"
#  release_tag: "4.4.9-x86_64"
```

When running `ansible-playbook -e @vars.yaml -e staticips=true tasks/main.yml` I got the error below.

```
TASK [Write out "domain.com" zone file] ******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'registry_host' is undefined"}
```

For a quick resolution I removed these line in template/zonefile.j2 and it run successfully.
```
{%if setup_registry %}
; Create entry for the local registry
{{ registry_host }}	IN	A	{{ helper.ipaddr }}
;
{% endif %}
```
